### ISSUE TITLE
Add Identify protocol

### ISSUE THREAD

**Issue by mhchia** [libp2p/py-libp2p#236] opened 2019-08-13 05:03 UTC
Identify protocol is called right after a connection is established. A working stream handler is wirtten in https://github.com/libp2p/py-libp2p/pull/175/files#diff-d849b88ca6d47c303e72e27bb20048d6, but the logic of logic of opening the stream and the tests are not finished yet.

### Reference
- Spec: https://github.com/libp2p/specs/tree/master/identify

**Comment by mhchia** [comment] 2019-08-19 11:21
Note: Removed `Interoperability` tag. Though `IdentifyConn` is called right after a connection is established in [basic_host](https://github.com/libp2p/go-libp2p/blob/master/p2p/host/basic/basic_host.go#L244), it seems not a must to finish [`Identify` request](https://github.com/libp2p/go-libp2p/blob/master/p2p/protocol/identify/id.go#L133-L170).

cc @ralexstokes

**Comment by ShadowJonathan** [comment] 2019-12-01 15:16
Possible duplicate of #358, or is this issue closed with that merge?

**Comment by ralexstokes** [comment] 2019-12-01 22:47
We should keep #358 but i think we can go ahead and close this... feel free to re-open @mhchia if you want to track something else here

**Closed by ralexstokes** 2019-12-01 22:47 UTC
